---
# =============================================================================
# CachyOS Package Lists
# Edit these lists to customize what gets installed on your machines.
# =============================================================================

# -----------------------------------------------------------------------------
# Pacman (native) packages
# -----------------------------------------------------------------------------
pacman_packages:
  # Shell & Terminal
  - zsh
  - kitty
  - tmux
  - zoxide
  - fzf
  - eza
  - bat
  - fastfetch
  - btop

  # Editors
  - neovim

  # Dev tools
  - git
  - git-delta
  - base-devel
  - ripgrep
  - fd
  - jq
  - go-yq
  - shellcheck
  - shfmt
  - mise

  # System tools
  - curl
  - wget
  - rsync
  - unzip
  - zip
  - bc
  - man-db
  - man-pages
  - strace
  - usbutils
  - smartmontools
  - pacman-contrib
  - inotify-tools
  - openssh
  - gnupg
  - pwgen

  # Fonts
  - ttf-jetbrains-mono-nerd
  - noto-fonts-emoji
  - ttf-freefont
  - fontconfig

  # Network
  - dnsutils
  - openbsd-netcat
  - whois

  # Media
  - ffmpeg
  - mpv
  - imagemagick
  - libqalculate

  # GUI / Desktop
  - firefox
  - ghostty
  - gimp
  - keepassxc
  - libreoffice-fresh
  - thunar
  - thunar-archive-plugin
  - xarchiver
  - zathura
  - zathura-pdf-mupdf
  - zathura-djvu

  # Wayland / Display
  - niri
  - waybar
  - mako
  - swaybg
  - swayidle
  - swaylock
  - uwsm
  - grim
  - slurp
  - wl-clipboard
  - wev
  - xwayland-satellite
  - brightnessctl
  - hyprpicker

  # Audio
  - pipewire
  - pipewire-alsa
  - pipewire-jack
  - pipewire-pulse
  - wireplumber
  - mpd
  - mpd-mpris

  # Docker
  - docker
  - docker-buildx
  - docker-compose

  # Misc
  - aspell
  - offlineimap
  - tumbler
  - ffmpegthumbnailer
  - satty
  - tesseract-data-eng
  - timidity++
  - obs-studio
  - lact
  - rmpc
  - wiremix

  # XDG portals
  - xdg-desktop-portal-gnome
  - xdg-desktop-portal-gtk

# -----------------------------------------------------------------------------
# AUR packages
# -----------------------------------------------------------------------------
aur_packages:
  # App launcher
  - walker-bin
  - wlrctl

  # Elephant plugins
  - elephant-bin
  - elephant-calc-bin
  - elephant-clipboard-bin
  - elephant-desktopapplications-bin
  - elephant-files-bin
  - elephant-menus-bin
  - elephant-providerlist-bin
  - elephant-runner-bin
  - elephant-symbols-bin
  - elephant-unicode-bin
  - elephant-websearch-bin
  - elephant-windows-bin

  # Apps
  - wavebox-beta
  - tana
  - spotifyd

  # Tools
  - yazi

# -----------------------------------------------------------------------------
# Flatpak packages
# -----------------------------------------------------------------------------
flatpak_packages:
  - com.daniel15.wcc

# -----------------------------------------------------------------------------
# AppImages (manual download required - these are just reminders)
# -----------------------------------------------------------------------------
appimage_reminders:
  - name: Espanso
    url: https://github.com/espanso/espanso/releases
    destination: ~/Applications/

  # Additional AUR packages from snapshot
  - 1password-beta
  - appimagelauncher
  - clickup
  - dropbox
  - espanso-wayland
  - gearlever
  - google-chrome
  - naps2
  - qownnotes
  - slack-desktop
  - sublime-text-4
  - zoom
  - zen-browser-bin
  - wallust

  # Additional pacman packages from snapshot
  - alacritty
  - audacity
  - betterbird-bin
  - chromium
  - claws-mail
  - code
  - discord
  - emacs
  - flatpak
  - gimp
  - hypridle
  - hyprland
  - hyprlock
  - inkscape
  - isync
  - joplin-desktop
  - kdenlive
  - kdeconnect
  - localsend
  - meld
  - micro
  - mpv-mpris
  - mutt
  - nvtop
  - nwg-displays
  - nwg-look
  - onlyoffice-bin
  - pavucontrol
  - playerctl
  - qalculate-gtk
  - ranger
  - rofi
  - shotcut
  - signal-desktop
  - solaar
  - spotify-launcher
  - swaync
  - swww
  - task
  - taskwarrior-tui
  - thunderbird
  - ufw
  - unrar
  - ventoy-bin
  - vlc
  - wayvnc
  - wlogout
  - wps-office
  - yt-dlp
  - zsh

  # System tools
  - exfatprogs
  - dosfstools
  - btrfs-progs
  - btrfs-assistant
  - snapper
  - fwupd
  - pv
  - duf
  - croc
  - lsd
  - tree
  - glances
  - speedtest-cli
  - reflector
  - pkgfile
  - rebuild-detector
  - plocate
  - hdparm
  - hwinfo
  - nvtop
  - cpupower
  - ufw
  - iwd
  - bluez
  - bluez-utils
  - blueman
  - cups
  - cups-filters
  - cups-pdf
  - system-config-printer
  - power-profiles-daemon
  - pamixer
  - pavucontrol
  - playerctl
  - cliphist
  - swappy
  - gvfs
  - gvfs-mtp

  # Fonts
  - ttf-jetbrains-mono
  - ttf-fira-code
  - ttf-meslo-nerd
  - ttf-liberation
  - ttf-dejavu
  - ttf-droid
  - ttf-bitstream-vera
  - ttf-opensans
  - otf-font-awesome
  - noto-fonts
  - noto-fonts-cjk
  - noto-color-emoji-fontconfig
  - awesome-terminal-fonts
  - opendesktop-fonts

  # Media
  - haruna
  - shotwell
  - vlc
  - vlc-plugins-all
  - cava
  - spotify-launcher
  - mpv-mpris
  - kdenlive
  - shotcut

  # Apps
  - evolution
  - geany
  - geany-plugins
  - mousepad
  - inkscape
  - audacity
  - audacious
  - impala
  - loupe
  - meld
  - mercurial
  - micro
  - nano-syntax-highlighting
  - mutt
  - task
  - taskwarrior-tui
  - ranger
  - yt-dlp
  - w3m
  - lynx
  - elinks
  - links
  - conky
  - cmatrix
  - cowsay
  - ponysay
  - fortune-mod

  # Wayland/Display extras
  - swww
  - swaync
  - wlogout
  - nwg-displays
  - nwg-look
  - quickshell
  - rofi
  - xsettingsd
  - hyprpolkitagent
  - hypridle
  - egl-wayland
  - qt6-wayland
  - xdg-desktop-portal
  - xdg-desktop-portal-hyprland
  - xdg-user-dirs

  # Printing
  - ghostscript
  - gutenprint
  - foomatic-db
  - foomatic-db-engine
  - foomatic-db-nonfree
  - splix

  # Network
  - networkmanager-openvpn
  - modemmanager
  - nfs-utils
  - dnsmasq
  - wpa_supplicant
  - wayvnc

  # Misc
  - gnome-keyring
  - libdvdcss
  - poppler-glib
  - resvg
  - ffmpegthumbs
  - gst-libav
  - gst-plugins-bad
  - gst-plugins-ugly
  - gst-plugin-pipewire
  - libva-nvidia-driver
  - lib32-nvidia-utils
  - opencl-nvidia
  - lib32-opencl-nvidia
  - nvidia-utils
  - nvidia-settings
  - mesa-utils
  - vulkan-icd-loader
  - lib32-vulkan-icd-loader
  - yad
  - swappy
  - solaar
  - localsend
  - ventoy-bin
  - onlyoffice-bin
  - wps-office
  - emacs
  - isync
  - claws-mail
  - thunar-volman
  - alsa-utils
  - alsa-plugins
  - alsa-firmware
  - paru
  - yay

  # Additional AUR
  - geany-themes
  - gtk-engine-murrine
  - ttf-victor-mono
  - spotify-tui-bin
  - urlview
  - t-prot
  - thunar-dropbox

  # KDE Plasma desktop
  - plasma-desktop
  - plasma-workspace
  - plasma-nm
  - plasma-pa
  - plasma-firewall
  - plasma-integration
  - plasma-systemmonitor
  - plasma-thunderbolt
  - plasma-browser-integration
  - plasma-x11-session
  - powerdevil
  - kscreen
  - kwallet-pam
  - kwalletmanager
  - kdeplasma-addons
  - kde-gtk-config
  - libplasma
  - breeze-gtk
  - kvantum
  - qt5ct
  - qt6ct
  - qt6-wayland
  - phonon-qt6-vlc
  - sddm
  - sddm-kcm
  - bluedevil
  - plasma-thunderbolt

  # KDE apps
  - dolphin
  - dolphin-plugins
  - kate
  - konsole
  - gwenview
  - okular
  - spectacle
  - ark
  - kcalc
  - kdialog
  - kinfocenter
  - kio-admin
  - filelight
  - kdegraphics-thumbnailers
  - ffmpegthumbs
  - loupe
  - haruna
  - kdeconnect
  - plasma-browser-integration

  # Additional system/utility packages
  - accountsservice
  - adobe-source-code-pro-fonts
  - adobe-source-han-sans-cn-fonts
  - adobe-source-han-sans-jp-fonts
  - adobe-source-han-sans-kr-fonts
  - ansible
  - bash-completion
  - bind
  - bluez-libs
  - char-white
  - dmidecode
  - exfatprogs
  - fsarchiver
  - gnome-system-monitor
  - gsfonts
  - haveged
  - hwdetect
  - iptables-nft
  - kde-applications-meta
  - libgsf
  - libopenraw
  - libspng
  - libwnck3
  - lsb-release
  - lsscsi
  - mdadm
  - mtools
  - nss-mdns
  - ntp
  - octopi
  - os-prober
  - python-defusedxml
  - python-packaging
  - python-pyquery
  - python-tzdata
  - sg3_utils
  - speech-dispatcher
  - sysfsutils
  - texinfo
  - umockdev
  - usb_modeswitch
  - vim
  - xdg-desktop-portal-kde
  - xfsprogs
  - xl2tpd
